### ISSUE TITLE
Detect filetype based on shebang

### ISSUE THREAD

**Issue by michaelskyba** [kyx0r/neatvi#6]
Is this possible (from the README, I don't think so, but I wanted to make sure)? If not, could you give a hint on how I could implement it (I'm not at all familiar with C)?

My use case is that I have shell scripts without extensions, but with "#!/bin/sh" at the start, and would like to trigger "sh" syntax highlighting for them.

**Comment by kyx0r** [comment]
Hello, I've have encountered this nuisance myself, and thought about it before. 
The nature of the problem requires reading certain arbitary predefined parts of the file. Well, I've concluded that it is not a good design decision to do this in my editor. The extra potential code for such checks would be run over any file, adding more ambiguos behavior. Just not a goal for a project like this, which aims to solve more so fundamental problems.

Generally just use ```:ft sh``` to set the file type, after opening it.

Or use this patch: https://0x0.st/-VJ1.patch
Hopefully that is clear enough on how to use it and maybe extend in the future for other types of "shebangs"

And yes, welcome to this little project of mine, generally not everything about neatvi is documented in readme, it assumes user to at least read vi.c a few times just to know how to change anything you want. You can discover a lot of new things.
If you have any other questions feel free to message me.

Regards, 
Kyryl

**Comment by michaelskyba** [comment]
Thank you for such a detailed reply! `:ft sh` is a little inconvenient, but your patch worked perfectly! By slightly modifying it, I was able to additionally get `#!/usr/bin/python`, and should now be able to competently check other arbitrary locations in the file.

I agree that it's better to have something like this outside of the main codebase; there's nothing inherently significant about shebangs, and in the future they could even be deprecated. It wouldn't make sense for neatvi to have to follow those changes around.

I will try to read vi.c (and hopefully understand some of it), as you suggested. Thank you again, for helping me, and for making this project. I've never seen a text editor (besides vi, which doesn't have enough basic features to be usable for me) load so fast.
